import type { TrollAction } from "@/types/main";

const trollActions: TrollAction[] = [
  {
    type: "fart_type_1",
    icon: "wind",
    label: "TROLL_FART_LABEL_1",
    description: "TROLL_FART_DESCRIPTION",
    buttonLabel: "TROLL_FART_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "fart_type_2",
    icon: "wind",
    label: "TROLL_FART_LABEL_2",
    description: "TROLL_FART_DESCRIPTION",
    buttonLabel: "TROLL_FART_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "attack_npc",
    icon: "person-rifle",
    label: "TROLL_ATTACK_NPC_LABEL",
    description: "TROLL_ATTACK_NPC_DESCRIPTION",
    buttonLabel: "TROLL_ATTACK_NPC_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "attack_animal",
    icon: "dog",
    label: "TROLL_ATTACK_ANIMAL_LABEL",
    description: "TROLL_ATTACK_ANIMAL_DESCRIPTION",
    buttonLabel: "TROLL_ATTACK_ANIMAL_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "kidnap",
    icon: "mask",
    label: "TROLL_KIDNAP_LABEL",
    description: "TROLL_KIDNAP_DESCRIPTION",
    buttonLabel: "TROLL_KIDNAP_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "ufo_kidnap",
    icon: "user-astronaut",
    label: "TROLL_UFO_KIDNAP_LABEL",
    description: "TROLL_UFO_KIDNAP_DESCRIPTION",
    buttonLabel: "TROLL_UFO_KIDNAP_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "flame",
    icon: "fire",
    label: "TROLL_FLAME_LABEL",
    description: "TROLL_FLAME_DESCRIPTION",
    buttonLabel: "TROLL_FLAME_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "force_control_player",
    icon: "gamepad",
    label: "TROLL_FORCE_CONTROL_PLAYER_LABEL",
    description: "TROLL_FORCE_CONTROL_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_FORCE_CONTROL_PLAYER_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "fake_lag",
    icon: "wifi",
    label: "TROLL_FAKE_LAG_LABEL",
    description: "TROLL_FAKE_LAG_DESCRIPTION",
    buttonLabel: "TROLL_FAKE_LAG_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "reverse_control",
    icon: "rotate-left",
    label: "TROLL_REVERSE_CONTROL_LABEL",
    description: "TROLL_REVERSE_CONTROL_DESCRIPTION",
    buttonLabel: "TROLL_REVERSE_CONTROL_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "clone_follow",
    icon: "user-plus",
    label: "TROLL_CLONE_FOLLOW_LABEL",
    description: "TROLL_CLONE_FOLLOW_DESCRIPTION",
    buttonLabel: "TROLL_CLONE_FOLLOW_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "flip_vehicle",
    icon: "car-burst",
    label: "TROLL_FLIP_VEHICLE_LABEL",
    description: "TROLL_FLIP_VEHICLE_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_VEHICLE_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "flip_player",
    icon: "user-injured",
    label: "TROLL_FLIP_PLAYER_LABEL",
    description: "TROLL_FLIP_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_PLAYER_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "nuke_alert_sound",
    icon: "circle-radiation",
    label: "TROLL_NUKE_ALERT_SOUND_LABEL",
    description: "TROLL_NUKE_ALERT_SOUND_DESCRIPTION",
    buttonLabel: "TROLL_NUKE_ALERT_SOUND_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "door_open_close",
    icon: "car-side",
    label: "TROLL_DOOR_OPEN_CLOSE_LABEL",
    description: "TROLL_DOOR_OPEN_CLOSE_DESCRIPTION",
    buttonLabel: "TROLL_DOOR_OPEN_CLOSE_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "ultra_slow_walk",
    icon: "person-walking-with-cane",
    label: "TROLL_ULTRA_SLOW_WALK_LABEL",
    description: "TROLL_ULTRA_SLOW_WALK_DESCRIPTION",
    buttonLabel: "TROLL_ULTRA_SLOW_WALK_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "random_time_cycle",
    icon: "business-time",
    label: "TROLL_RANDOM_TIME_CYCLE_LABEL",
    description: "TROLL_RANDOM_TIME_CYCLE_DESCRIPTION",
    buttonLabel: "TROLL_RANDOM_TIME_CYCLE_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "2d_game",
    icon: "square",
    label: "TROLL_2D_GAME_LABEL",
    description: "TROLL_2D_GAME_DESCRIPTION",
    buttonLabel: "TROLL_2D_GAME_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "flip_camera",
    icon: "video",
    label: "TROLL_FLIP_CAMERA_LABEL",
    description: "TROLL_FLIP_CAMERA_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_CAMERA_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "fov_camera",
    icon: "video",
    label: "TROLL_FOV_CAMERA_LABEL",
    description: "TROLL_FOV_CAMERA_DESCRIPTION",
    buttonLabel: "TROLL_FOV_CAMERA_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "ghost",
    icon: "ghost",
    label: "TROLL_GHOST_LABEL",
    description: "TROLL_GHOST_DESCRIPTION",
    buttonLabel: "TROLL_GHOST_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "local_invisibility",
    icon: "user-secret",
    label: "TROLL_LOCAL_INVISIBILITY_LABEL",
    description: "TROLL_LOCAL_INVISIBILITY_DESCRIPTION",
    buttonLabel: "TROLL_LOCAL_INVISIBILITY_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "disable_lights",
    icon: "lightbulb",
    label: "TROLL_DISABLE_LIGHTS_LABEL",
    description: "TROLL_DISABLE_LIGHTS_DESCRIPTION",
    buttonLabel: "TROLL_DISABLE_LIGHTS_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "shrink_player",
    icon: "arrows-alt-v",
    label: "TROLL_SHRINK_PLAYER_LABEL",
    description: "TROLL_SHRINK_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_SHRINK_PLAYER_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "scale_up_player",
    icon: "arrows-alt-v",
    label: "TROLL_SCALE_UP_PLAYER_LABEL",
    description: "TROLL_SCALE_UP_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_SCALE_UP_PLAYER_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "breake_vehicle_wheel",
    icon: "circle",
    label: "TROLL_BREAKE_VEHICLE_WHEEL_LABEL",
    description: "TROLL_BREAKE_VEHICLE_WHEEL_DESCRIPTION",
    buttonLabel: "TROLL_BREAKE_VEHICLE_WHEEL_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "ultra_fog",
    icon: "smog",
    label: "TROLL_ULTRA_FOG_LABEL",
    description: "TROLL_ULTRA_FOG_DESCRIPTION",
    buttonLabel: "TROLL_ULTRA_FOG_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "vehicle_low_gravity",
    icon: "moon",
    label: "TROLL_VEHICLE_LOW_GRAVITY_LABEL",
    description: "TROLL_VEHICLE_LOW_GRAVITY_DESCRIPTION",
    buttonLabel: "TROLL_VEHICLE_LOW_GRAVITY_BUTTON",
    toggle: true,
    isSync: true,
  },
  {
    type: "shockwave",
    icon: "wave-square",
    label: "TROLL_SHOCKWAVE_LABEL",
    description: "TROLL_SHOCKWAVE_DESCRIPTION",
    buttonLabel: "TROLL_SHOCKWAVE_BUTTON",
    toggle: false,
    isSync: true,
  },
  {
    type: "clone_circle",
    icon: "circle-nodes",
    label: "TROLL_CLONE_CIRCLE_LABEL",
    description: "TROLL_CLONE_CIRCLE_DESCRIPTION",
    buttonLabel: "TROLL_CLONE_CIRCLE_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "low_poly",
    icon: "cubes",
    label: "TROLL_LOW_POLY_LABEL",
    description: "TROLL_LOW_POLY_DESCRIPTION",
    buttonLabel: "TROLL_LOW_POLY_BUTTON",
    toggle: true,
    isSync: false,
  },
  {
    type: "snow_weather",
    icon: "snowflake",
    label: "TROLL_SNOW_WEATHER_LABEL",
    description: "TROLL_SNOW_WEATHER_DESCRIPTION",
    buttonLabel: "TROLL_SNOW_WEATHER_BUTTON",
    toggle: true,
    isSync: false,
  },
];

export default trollActions;
