import type { TrollAction } from "@/types/main";

const trollActions: TrollAction[] = [
  {
    type: "fart_type_1",
    icon: "wind",
    label: "TROLL_FART_LABEL_1",
    description: "TROLL_FART_DESCRIPTION",
    buttonLabel: "TROLL_FART_BUTTON",
  },
  {
    type: "fart_type_2",
    icon: "wind",
    label: "TROLL_FART_LABEL_2",
    description: "TROLL_FART_DESCRIPTION",
    buttonLabel: "TROLL_FART_BUTTON",
    toggle: true,
  },
  {
    type: "attack_npc",
    icon: "person-rifle",
    label: "TROLL_ATTACK_NPC_LABEL",
    description: "TROLL_ATTACK_NPC_DESCRIPTION",
    buttonLabel: "TROLL_ATTACK_NPC_BUTTON",
    toggle: true,
  },
  {
    type: "attack_animal",
    icon: "dog",
    label: "TROLL_ATTACK_ANIMAL_LABEL",
    description: "TROLL_ATTACK_ANIMAL_DESCRIPTION",
    buttonLabel: "TROLL_ATTACK_ANIMAL_BUTTON",
    toggle: true,
  },
  {
    type: "kidnap",
    icon: "mask",
    label: "TROLL_KIDNAP_LABEL",
    description: "TROLL_KIDNAP_DESCRIPTION",
    buttonLabel: "TROLL_KIDNAP_BUTTON",
  },
  {
    type: "ufo_kidnap",
    icon: "user-astronaut",
    label: "TROLL_UFO_KIDNAP_LABEL",
    description: "TROLL_UFO_KIDNAP_DESCRIPTION",
    buttonLabel: "TROLL_UFO_KIDNAP_BUTTON",
  },
  {
    type: "flame",
    icon: "fire",
    label: "TROLL_FLAME_LABEL",
    description: "TROLL_FLAME_DESCRIPTION",
    buttonLabel: "TROLL_FLAME_BUTTON",
    toggle: true,
  },
  {
    type: "force_control_player",
    icon: "gamepad",
    label: "TROLL_FORCE_CONTROL_PLAYER_LABEL",
    description: "TROLL_FORCE_CONTROL_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_FORCE_CONTROL_PLAYER_BUTTON",
    toggle: true,
  },
  {
    type: "fake_lag",
    icon: "wifi",
    label: "TROLL_FAKE_LAG_LABEL",
    description: "TROLL_FAKE_LAG_DESCRIPTION",
    buttonLabel: "TROLL_FAKE_LAG_BUTTON",
    toggle: true,
  },
  {
    type: "reverse_control",
    icon: "rotate-left",
    label: "TROLL_REVERSE_CONTROL_LABEL",
    description: "TROLL_REVERSE_CONTROL_DESCRIPTION",
    buttonLabel: "TROLL_REVERSE_CONTROL_BUTTON",
    toggle: true,
  },
  {
    type: "clone_follow",
    icon: "user-plus",
    label: "TROLL_CLONE_FOLLOW_LABEL",
    description: "TROLL_CLONE_FOLLOW_DESCRIPTION",
    buttonLabel: "TROLL_CLONE_FOLLOW_BUTTON",
    toggle: true,
  },
  {
    type: "flip_vehicle",
    icon: "car-burst",
    label: "TROLL_FLIP_VEHICLE_LABEL",
    description: "TROLL_FLIP_VEHICLE_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_VEHICLE_BUTTON",
  },
  {
    type: "flip_player",
    icon: "user-injured",
    label: "TROLL_FLIP_PLAYER_LABEL",
    description: "TROLL_FLIP_PLAYER_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_PLAYER_BUTTON",
  },
  {
    type: "nuke_alert_sound",
    icon: "circle-radiation",
    label: "TROLL_NUKE_ALERT_SOUND_LABEL",
    description: "TROLL_NUKE_ALERT_SOUND_DESCRIPTION",
    buttonLabel: "TROLL_NUKE_ALERT_SOUND_BUTTON",
    toggle: true,
  },
  {
    type: "door_open_close",
    icon: "car-side",
    label: "TROLL_DOOR_OPEN_CLOSE_LABEL",
    description: "TROLL_DOOR_OPEN_CLOSE_DESCRIPTION",
    buttonLabel: "TROLL_DOOR_OPEN_CLOSE_BUTTON",
    toggle: true,
  },
  {
    type: "ultra_slow_walk",
    icon: "person-walking-with-cane",
    label: "TROLL_ULTRA_SLOW_WALK_LABEL",
    description: "TROLL_ULTRA_SLOW_WALK_DESCRIPTION",
    buttonLabel: "TROLL_ULTRA_SLOW_WALK_BUTTON",
    toggle: true,
  },
  {
    type: "random_time_cycle",
    icon: "business-time",
    label: "TROLL_RANDOM_TIME_CYCLE_LABEL",
    description: "TROLL_RANDOM_TIME_CYCLE_DESCRIPTION",
    buttonLabel: "TROLL_RANDOM_TIME_CYCLE_BUTTON",
    toggle: true,
  },
  {
    type: "2d_game",
    icon: "square",
    label: "TROLL_2D_GAME_LABEL",
    description: "TROLL_2D_GAME_DESCRIPTION",
    buttonLabel: "TROLL_2D_GAME_BUTTON",
    toggle: true,
  },
  {
    type: "flip_camera",
    icon: "video",
    label: "TROLL_FLIP_CAMERA_LABEL",
    description: "TROLL_FLIP_CAMERA_DESCRIPTION",
    buttonLabel: "TROLL_FLIP_CAMERA_BUTTON",
    toggle: true,
  },
  {
    type: "ghost",
    icon: "ghost",
    label: "TROLL_GHOST_LABEL",
    description: "TROLL_GHOST_DESCRIPTION",
    buttonLabel: "TROLL_GHOST_BUTTON",
    toggle: true,
  },
];

export default trollActions;
